server:
  port: 8010
spring:
  application:
    name: springcloud-demo-consumer-movie-ribbon
eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8761/eureka/                         #localhost
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/    #HA
  instance:
#    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}        # 将Instance ID设置成IP:端口的形式