server:
  port: 8761                    # 指定该Eureka实例的端口
spring:
  application:
    name: springcloud-demo-discovery-eureka
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# 参考文档：http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#_standalone_mode
# 参考文档：http://my.oschina.net/buwei/blog/618756

---
spring:
  profiles: peer1                                                       # 指定profile=peer1
server:
  port: 8761                                                             # 指定该Eureka实例的端口
eureka:
  instance:
    hostname: peer1                                                     # 指定当profile=peer1时，主机名是peer1
#    prefer-ip-address: true                                            #unavailable-replicas not to available-replicas
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}        # 将Instance ID设置成IP:端口的形式
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/                             # 将自己注册到peer2这个Eureka上面去
---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
#    prefer-ip-address: true                                            #unavailable-replicas not to available-replicas
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}        # 将Instance ID设置成IP:端口的形式
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
