server:
  port: 8761                    # 指定该Eureka实例的端口
spring:
  application:
    name: springcloud-demo-discovery-eureka
eureka:
#  server:
#    enableSelfPreservation: false                           #关闭自我保护
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# 参考文档：http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#_standalone_mode
# 参考文档：http://my.oschina.net/buwei/blog/618756

---
spring:
  profiles: peer1                                                       # 指定profile=peer1
server:
  port: 8761                                                             # 指定该Eureka实例的端口
eureka:
  instance:
    hostname: peer1                                                     # 指定当profile=peer1时，主机名是peer1
    #    prefer-ip-address: true                                            #unavailable-replicas not to available-replicas
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}        # 将Instance ID设置成IP:端口的形式
    lease-renewal-interval-in-seconds: 5                                #租期更新时间间隔（默认30秒）
    lease-expiration-duration-in-seconds: 15                            #租期到期时间（默认90秒）不怕出错的话，时间可以更短
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/                            # 将自己注册到peer2这个Eureka上面去
---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
    #    prefer-ip-address: true                                            #unavailable-replicas not to available-replicas
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}        # 将Instance ID设置成IP:端口的形式
    lease-renewal-interval-in-seconds: 5                                #租期更新时间间隔（默认30秒）
    lease-expiration-duration-in-seconds: 15                            #租期到期时间（默认90秒）不怕出错的话，时间可以更短
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
